### ISSUE TITLE
Start without the github actions workflow file

### ISSUE THREAD

**Issue by aaronpowell** [manekinekko/swa-emulator#15]
Currently, you are required to have created a GitHub Actions workflow file before you're able to use the emulator.

This is because the emulator reads a bunch of stuff out of the workflow file, but it can make for a challenging development flow as you have to have deployed the application before you're able to use the emulator.

It'd be useful if there was a way that you could run the emulator without creating the workflow first.

**Comment by aaronpowell** [comment]
I think that any information that is read from the workflow file should also be exposed as cli arguments, and if you provide those arguments then it'll use them rather than reading out of the workflow file.

**Comment by manekinekko** [comment]
Great feedback!
