### ISSUE TITLE
Providing app/api uri should prevent the emulator from starting its own

### ISSUE THREAD

**Issue by aaronpowell** [manekinekko/swa-emulator#17]
Let's say I want to run the APP and/or API myself (maybe they run a compiler like TypeScript), I would run the emulator like so:

```
$> swa --app-uri=http://localhost:3000 --api-uri=http://localhost:7071
```

But when it starts up, it'll attempt to run its own proxies for those, and in particular the API will fail as the port is already in use.

Since there's no need for these proxies to be run by the emulator, it should skip trying to start them if you provide the uri.

**Comment by manekinekko** [comment]
I've included this in #19 Now you would do:

```
$> swa --use-app=http://localhost:3000 --use-api=http://localhost:7071
```

Would this would for you?

FYI, `--app-uri` and `--api-uri` are used to set the URI for the built-in proxies.
