### ISSUE TITLE
Auth complete workflow doesn't match SWA

### ISSUE THREAD

**Issue by aaronpowell** [manekinekko/swa-emulator#29]
**Description of bug**

When the auth pipeline hits `/.auth/complete` the emulator responds with a 302 that sets the `location` header the emulator host.

**Expected outcome**

It should return a 200 response with a HTML chunk that does an auth redirect to the path provided in `post_login_redirect_uri` on the `/.auth/login/<provider>` query string.

Here's a sample HTML response:

```html
<html><head><title>Working...</title></head><body><form method="GET" name="hiddenform" action="https://purple-plant-04c92a01e.azurestaticapps.net/authentication/login-callback/e71e4fa3-6298-4c01-ab1d-882ab0758110"><noscript><p>Script is disabled. Click Submit to continue.</p><input type = "submit" value = "Submit" /></noscript></form><script language = "javascript">document.forms[0].submit();</script></body></html>
```

**Comment by manekinekko** [comment]
Fixed in #30
